### ISSUE TITLE
Проблемки ;)

### ISSUE THREAD

**Issue by novachok** [Kloud333/PHP_Lab#1]
https://github.com/Kloud333/PHP_Lab/blob/master/Homework_1_Basics/index.php#L7
результат буде "HelloWorld" - а треба - "Hello World"

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_1_Basics/index.php#L49
не правильно, наприклад рік 1900 - не був високосним

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_1_Basics/index.php#L63
якщо вибираємо до кінця рядка - то вказувати довжину не обов'язково

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_1_Basics/index.php#L68
не правильно - уважно подивись по чому ти ітеруєшся

**Comment by Kloud333** [comment]
Проблемки це добре. ) Отже є чому вчитись і на що звертати увагу. Виправлю. ;)

**Comment by Kloud333** [comment]
Виправив.
