### ISSUE TITLE
#3

### ISSUE THREAD

**Issue by novachok** [Kloud333/PHP_Lab#2]
https://github.com/Kloud333/PHP_Lab/blob/master/Homework_3_Arrays/index.php#L8
робота з масивом через "рядок" - не дуже доцільно, це можна було б зробити через array_fill

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_3_Arrays/index.php#L24
дуже цікаве рішення!!

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_3_Arrays/index.php#L78
тут краще було б використати usort з колбек функцією

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_3_Arrays/index.php#L102
це найкраще рішення в групі, дякую!!!

https://github.com/Kloud333/PHP_Lab/blob/master/Homework_3_Arrays/index.php#L126
тут погано виконана конвертація типу - згадуємо першу лекцію

**Comment by Kloud333** [comment]
Спасибі за коментарі та зауваження. =) Зрозумів та виправив.

**Comment by novachok** [comment]
https://github.com/Kloud333/PHP_Lab/blob/master/Homework_3_Arrays/index.php#L78
ще правильно визначать ситуацію - коли $a == $b

**Comment by Kloud333** [comment]
Логічно. Щось пропустив її. Поправив.
